version: "3.1"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ssqlserver2019
    restart: always 
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
